# Generated by Django 5.2.6 on 2025-10-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekerProfile', '0001_initial'),
    ]

    operations = [
    ]
