# Generated by Django 5.2.6 on 2025-10-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekerProfile', '0002_auto_20251013_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='JobSeekerProfile.jobseekerprofile'),
        ),
    ]
