# Generated by Django 5.2.5 on 2025-10-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekerProfile', '0003_alter_resume_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='data',
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(null=True, upload_to='resume-file/'),
        ),
    ]
