# Generated by Django 5.2.5 on 2025-10-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekerProfile', '0004_remove_resume_data_alter_resume_file'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resume',
            name='one_default_resume_per_profile',
        ),
    ]
