# Generated by Django 5.2.7 on 2025-10-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekerProfile', '0004_alter_resume_file'),
        ('JobSeekerProfile', '0005_remove_resume_one_default_resume_per_profile'),
    ]

    operations = [
    ]
