# Generated by Django 5.2.5 on 2025-10-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=255)),
                ('content', models.TextField()),
                ('contact_email', models.EmailField(default='support@jobseeker.com', max_length=254)),
                ('contact_address', models.TextField(default='JobSeeker Inc., 123 Career Street, City, Country')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
