# Generated by Django 5.2.5 on 2025-10-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='contact_address',
            field=models.TextField(default='JobSeeker Inc., 123 Career Street, City, Country', null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='contact_email',
            field=models.EmailField(default='support@jobseeker.com', max_length=254, null=True),
        ),
    ]
