# Generated by Django 5.2.5 on 2025-10-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_alter_privacypolicy_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
