# Generated by Django 5.2.5 on 2025-10-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_privacypolicy_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=255)),
                ('content', models.TextField()),
                ('mission_statement', models.TextField(default='To connect job seekers with their dream jobs.')),
                ('vision_statement', models.TextField(default='To be the leading platform for job seekers worldwide.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
