# Generated by Django 5.2.5 on 2025-10-20 01:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission_statement',
            field=ckeditor.fields.RichTextField(default='To connect job seekers with their dream jobs.'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision_statement',
            field=ckeditor.fields.RichTextField(default='To be the leading platform for job seekers worldwide.'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
