# Generated by Django 5.2.5 on 2025-10-04 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployerProfile', '0002_employerprofile_created_at_and_more'),
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='EmployerProfile.employerprofile'),
        ),
    ]
