# Generated by Django 5.2.5 on 2025-10-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_alter_jobs_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='max_applicants',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of allowed applicants', null=True),
        ),
    ]
