# Generated by Django 5.2.5 on 2025-10-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_jobs_max_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='max_applicants',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of allowed applicants'),
        ),
    ]
