# Generated by Django 5.2.5 on 2025-10-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_alter_jobs_max_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('FULL', 'Full-time'), ('PART', 'Part-time'), ('INTERN', 'Internship'), ('REMOTE', 'Remote')], default='FULL'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(choices=[('MO', 'MRAUK-U'), ('MB', 'MINBRAR'), ('SIT', 'SITTWE'), ('RD', 'RETHEEDAUNG'), ('MD', 'MAUNGDAW'), ('KP', 'KYAWTPYHU'), ('TD', 'THANDWE'), ('TG', 'TOUNGUP'), ('AN', 'ANN'), ('PNG', 'PONNAGYUN'), ('KT', 'KYAUKTAW'), ('RM', 'RAMREE'), ('MA', 'MANAUNG'), ('GW', 'GWA'), ('PT', 'PAUKTAW'), ('BTD', 'BUTHIDAUNG'), ('MB', 'MYEBON')], default='FULL'),
        ),
    ]
