# Generated by Django 5.2.6 on 2025-10-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_alter_jobs_job_type_alter_jobs_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(choices=[('MO', 'MRAUK-U'), ('MB', 'MINBRAR'), ('SIT', 'SITTWE'), ('RD', 'RETHEEDAUNG'), ('MD', 'MAUNGDAW'), ('KP', 'KYAWTPYHU'), ('TD', 'THANDWE'), ('TG', 'TOUNGUP'), ('AN', 'ANN'), ('PNG', 'PONNAGYUN'), ('KT', 'KYAUKTAW'), ('RM', 'RAMREE'), ('MA', 'MANAUNG'), ('GW', 'GWA'), ('PT', 'PAUKTAW'), ('BTD', 'BUTHIDAUNG'), ('MB', 'MYEBON')], default='MO'),
        ),
    ]
