# Generated by Django 5.2.5 on 2025-10-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_alter_jobs_job_type_alter_jobs_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='priority',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('FEATURED', 'Featured'), ('URGENT', 'Urgent')], default='NORMAL', help_text='Use FEATURED for top placement or URGENT for visible badge.', max_length=10, null=True),
        ),
    ]
