# Generated by Django 5.2.6 on 2025-10-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_alter_jobs_location'),
        ('Jobs', '0007_jobs_priority'),
    ]

    operations = [
    ]
