# Generated by Django 5.2.6 on 2025-10-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0008_merge_0006_alter_jobs_location_0007_jobs_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
