# Generated by Django 5.2.6 on 2025-11-18 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployerProfile', '0002_employerprofile_created_at_and_more'),
        ('Jobs', '0010_alter_jobs_job_type_alter_jobs_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployerProfile.employerprofile'),
        ),
        migrations.AddConstraint(
            model_name='jobcategory',
            constraint=models.UniqueConstraint(fields=('employer', 'name'), name='unique_category_per_employer'),
        ),
    ]
