# Generated by Django 5.2.6 on 2025-11-18 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0011_jobcategory_employer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobcategory',
            name='unique_category_per_employer',
        ),
        migrations.RemoveField(
            model_name='jobcategory',
            name='employer',
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='jobcategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_category_per_user'),
        ),
    ]
