# Generated by Django 5.2.7 on 2025-10-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
    ]
