# Generated by Django 5.2.6 on 2025-11-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_auto_20251023_0959'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_application_per_jobseeker_job',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('H', 'Hired'), ('RJ', 'Rejected'), ('R', 'Review'), ('SL', 'ShortList')], default='P', max_length=50, null=True),
        ),
    ]
