# Generated by Django 5.2.6 on 2025-11-22 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Application",
            "0003_remove_application_unique_application_per_jobseeker_job_and_more",
        ),
        ("Jobs", "0012_remove_jobcategory_unique_category_per_employer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Jobs.jobs"
            ),
        ),
    ]
